/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.SubjectInfo;
import org.chd.struts.adm.form.AddNewSubjectForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 10-26-2006
 * 
 * XDoclet definition:
 * @struts.action path="/adm/AddNewSubject" name="AddNewSubjectForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/adm/adm_main.jsp" redirect="true"
 */
public class AddNewSubjectAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddNewSubjectForm AddNewSubjectForm = (AddNewSubjectForm) form;
		
		String pageforward="";
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		try {
			String subject=new String(AddNewSubjectForm.getSubject().getBytes("ISO-8859-1"),"GBK");
			String typeName=new String(AddNewSubjectForm.getTypeName().getBytes("ISO-8859-1"),"GBK");
			String sourceName=new String(AddNewSubjectForm.getSourceName().getBytes("ISO-8859-1"),"GBK");
			String fieldName=new String(AddNewSubjectForm.getFieldName().getBytes("ISO-8859-1"),"GBK");
			String propertyName=new String(AddNewSubjectForm.getPropertyName().getBytes("ISO-8859-1"),"GBK");
			String majorName=new String(AddNewSubjectForm.getMajorName().getBytes("ISO-8859-1"),"GBK");
			String teacherAId=AddNewSubjectForm.getTeacherAId();
			String difficulty=AddNewSubjectForm.getDifficulty();
			tx = session.beginTransaction();
			SubjectInfo subjectInfo=new SubjectInfo(typeName,sourceName,propertyName,fieldName,subject,difficulty,teacherAId,majorName);
			session.save(subjectInfo);
			pageforward="success";
			tx.commit();
		}catch(Exception e)
		{
			if (tx != null)
				e.printStackTrace();
				tx.rollback();
			ActionErrors actionErrors = new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError(
					"errors.SQLError"));
			pageforward="failure";
		}
		finally{
			session.close();
		}
		return mapping.findForward(pageforward);
	}
}