/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.SubjectInfo;
import org.chd.struts.adm.form.ChangeSubjectForm;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/** 
 * MyEclipse Struts
 * Creation date: 04-24-2007
 * 
 * XDoclet definition:
 * @struts.action path="/adm/changeSubject" name="ChangeSubjectForm" input="/adm/select_subject.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/adm/index.jsp"
 * @struts.action-forward name="failure" path="/error.jsp" redirect="true"
 */
public class ChangeSubjectAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ChangeSubjectForm ChangeSubjectForm = (ChangeSubjectForm) form;
		String studentId=ChangeSubjectForm.getStudentId();
		String temp=ChangeSubjectForm.getSubjectId();
		Integer subjectId=Integer.parseInt(temp);
		String pageforward=null;
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		try {
			tx = session.beginTransaction();
			Criteria c2 = session.createCriteria(SubjectInfo.class);
			c2.add(Restrictions.eq("studentId", studentId));
		    SubjectInfo subject=(SubjectInfo)c2.uniqueResult();
		    if(subject!=null)
		    {
		      subject.setStudentId(null);
		      SubjectInfo newsubject=(SubjectInfo)session.get(SubjectInfo.class, subjectId);
			  if(newsubject.getStudentId()==null||newsubject.getStudentId().equals(""))
		      {
		         newsubject.setStudentId(studentId);
		         session.saveOrUpdate(newsubject);
			     pageforward="success";
		      }
			  else
			  {
				pageforward="failure";
			  }
			  tx.commit();
		   }
		    else
		    {
		    	pageforward="failure";
		    }
		}catch(Exception e)
		{
			if (tx != null)
				tx.rollback();
			pageforward="failure";
		}
		finally{
			session.close();
		}
		return mapping.findForward(pageforward);
	}
}