/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.AdminInfo;
import org.chd.struts.adm.form.JwyRegistrationForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 10-02-2006
 * 
 * XDoclet definition:
 * @struts.action path="/JwrRegistration" name="JwyRegistrationForm" input="/jwy_reg.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/jwy_reg.jsp" redirect="true"
 */
public class JwyRegistrationAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		JwyRegistrationForm JwyRegistrationForm = (JwyRegistrationForm) form;
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		String pageforward="";
		try {
			tx=session.beginTransaction();
			AdminInfo admin=new AdminInfo();
			admin.setAdminId(JwyRegistrationForm.getJwy_id());
			admin.setAdminPassword(JwyRegistrationForm.getJwy_password());
			admin.setAdminTag(false);
			session.save(admin);
			tx.commit();
			pageforward="success";
		} catch (Exception e) {
			if(tx!=null) tx.rollback();
			e.printStackTrace();
			ActionErrors actionErrors=new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError("errors.SQLError"));
			return new ActionForward(mapping.getInput());
		} finally {
			session.close();
		}
		return mapping.findForward(pageforward);
	}
}