/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.action;

import java.util.HashSet;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.SubjectInfo;
import org.chd.struts.adm.form.ShowSubjectNBysortForm;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2007
 * 
 * XDoclet definition:
 * @struts.action path="/adm/showSubjectNBySort" name="ShowSubjectNBySortForm" input="/adm/select_subject.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/adm/show_subject_bysort.jsp"
 * @struts.action-forward name="failure" path="/error.jsp" redirect="true"
 */
public class ShowSubjectNBySortAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ShowSubjectNBysortForm ShowSubjectNBySortForm = (ShowSubjectNBysortForm) form;
		String pageforward="failure";
		String sortname=ShowSubjectNBySortForm.getSortname();
		String studentId=ShowSubjectNBySortForm.getStudentId();
		System.out.println(studentId);
		Session session = HibernateSessionFactory.getSession();
		HashSet h=new HashSet();
		try
		{
			List subject_list = session.createCriteria(SubjectInfo.class).add(Restrictions.isNull("studentId")).list();
			Iterator i1=subject_list.iterator();
		if(sortname.equals("teacherId"))
		{ 
			String teacherId=ShowSubjectNBySortForm.getTeacherId();
			while(i1.hasNext())
			{
				SubjectInfo subject=(SubjectInfo)i1.next();
				if(subject.getTeacherAId()!=null&&subject.getTeacherAId().equals(teacherId))
					h.add(subject);
				pageforward="success";	
				request.setAttribute("SubjectSet", h);
			}
				
		}
		if(sortname.equals("difficulty"))
		{
			String difficulty=ShowSubjectNBySortForm.getDifficulty();
			while(i1.hasNext())
			{
				SubjectInfo subject=(SubjectInfo)i1.next();
				if(subject.getDifficulty()!=null&&subject.getDifficulty().equals(difficulty))
					h.add(subject);
				pageforward="success";		
				request.setAttribute("SubjectSet", h);
				
			}
		}
		if(sortname.equals("fieldName"))
		{
			String fieldName=ShowSubjectNBySortForm.getFieldName();
			while(i1.hasNext())
			{
				SubjectInfo subject=(SubjectInfo)i1.next();
				if(subject.getFieldName()!=null&&subject.getFieldName().equals(fieldName))
					h.add(subject);			
			}
			pageforward="success";
			request.setAttribute("SubjectSet", h);
		}
		request.setAttribute("studentId", studentId);	
		
	}catch(Exception e)
	{
		pageforward="failure";
	}
		return mapping.findForward(pageforward);
	}
	}
