/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.StudentInfo;
import org.chd.struts.adm.form.StudentRegistrationForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * MyEclipse Struts Creation date: 09-25-2006
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/StudentRegistration" name="StudentRegistrationForm"
 *                input="/studentRegistration.jsp" scope="request"
 *                validate="true"
 * @struts.action-forward name="success" path="/userInfoList.jsp"
 *                        redirect="true"
 */
public class StudentRegistrationAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StudentRegistrationForm StudentRegistrationForm = (StudentRegistrationForm) form;
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		String pageforward="";
		try {
			tx=session.beginTransaction();
			StudentInfo student=new StudentInfo();
			student.setStudentId(StudentRegistrationForm.getStudentId());
			student.setStudentName(new String(StudentRegistrationForm.getStudentName().getBytes("ISO-8859-1"),"GBK"));
			student.setStudentPassword(StudentRegistrationForm.getStudentPassword());
			student.setStudentSex(new String(StudentRegistrationForm.getStudentSex().getBytes("ISO-8859-1"),"GBK"));
			student.setMajorName(new String(StudentRegistrationForm.getMajorName().getBytes("ISO-8859-1"),"GBK"));
			student.setStudentEmail(new String(StudentRegistrationForm.getStudentEmail().getBytes("ISO-8859-1"),"GBK"));
			student.setStudentPhone(StudentRegistrationForm.getStudentPhone());
			student.setStudentClass(StudentRegistrationForm.getStudentClass());
			session.save(student);
			tx.commit();
			pageforward="success";
		} catch (Exception e) {
			if(tx!=null) tx.rollback();
			e.printStackTrace();
			ActionErrors actionErrors=new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError("errors.SQLError"));
			return new ActionForward(mapping.getInput());
		} finally {
			session.close();
		}
		return mapping.findForward(pageforward);
	}
}