/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.MisConstants;
import org.chd.entity.TeacherInfo;
import org.chd.struts.adm.form.TeacherInfoModifyForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 10-02-2006
 * 
 * XDoclet definition:
 * @struts.action path="/TeacherInfoModify" name="TeacherInfoModifyForm" input="/tea_info_show.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/tea_info_show.jsp" redirect="true"
 */
public class TeacherInfoModifyAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TeacherInfoModifyForm TeacherInfoModifyForm = (TeacherInfoModifyForm) form;
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		String pageforward = "";
		try {
			tx = session.beginTransaction();
			TeacherInfo t = new TeacherInfo();
			t.setFieldName(TeacherInfoModifyForm.getFieldName());
			t.setTeacherId(TeacherInfoModifyForm.getTeacherId());
			t.setTeacherName(TeacherInfoModifyForm.getTeacherName());
			t.setTeacherPassword(TeacherInfoModifyForm.getTeacherPassword());
			t.setTeacherSex(TeacherInfoModifyForm.getTeacherSex());
			t.setMajorName(TeacherInfoModifyForm.getMajorName());
			t.setPost(TeacherInfoModifyForm.getPost());
		    t.setTeacherPhone(TeacherInfoModifyForm.getTeacherPhone());
		    t.setTeacherEmail(TeacherInfoModifyForm.getTeacherEmail());
			session.saveOrUpdate(t);
			tx.commit();
			pageforward = "success";
			request.setAttribute(MisConstants.TEACHERINFO_KEY, t);
		} catch (Exception e) {
			e.printStackTrace();
			if (tx != null)
				tx.rollback();
			ActionErrors actionErrors = new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError(
					"errors.SQLError"));
			ActionForward returnActionForward = new ActionForward(mapping
					.getInput());
			return returnActionForward;
		} finally {
			session.close();
		}
		ActionForward returnActionForward = mapping.findForward(pageforward);
		return returnActionForward;
	}
}