/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 09-25-2006
 * 
 * XDoclet definition:
 * @struts.action path="/UserRegistration" name="UserRegistration" input="/userRegistration.jsp" scope="request" validate="true"
 * @struts.action-forward name="teacher" path="/teacherRegistration.jsp" redirect="true"
 * @struts.action-forward name="student" path="/studentRegistration.jsp" redirect="true"
 * @struts.action-forward name="admin" path="/adminRegistration.jsp" redirect="true"
 */
public class UserRegistration extends DispatchAction {
	
	public ActionForward StudentRegistration(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		return mapping.findForward("StudentRegistration");
	}
	public ActionForward TeacherRegistration(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		return mapping.findForward("TeacherRegistration");
	}
	public ActionForward AdminRegistration(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		return mapping.findForward("JwyRegistration");
	}
	
}
