/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.jwy.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.MisConstants;
import org.chd.entity.AdminInfo;
import org.chd.struts.jwy.form.JwyInfoModForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 03-26-2007
 * 
 * XDoclet definition:
 * @struts.action path="/jwy/JwyInfoMod" name="JwyInfoModForm" input="/jwy/jwy_info_modify.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/jwy/jwy_info_modify.jsp"
 * @struts.action-forward name="failure" path="/error.jsp"
 */
public class JwyInfoModAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		JwyInfoModForm JwyInfoModForm = (JwyInfoModForm) form;// TODO Auto-generated method stub
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		String pageforward="";
		try {
			tx=session.beginTransaction();
			AdminInfo admin=new AdminInfo();
			admin.setAdminId(JwyInfoModForm.getAdminId());
			admin.setAdminPassword(JwyInfoModForm.getAdminPassword());
			admin.setAdminTag(false);
			request.getSession().setAttribute(MisConstants.JWYINFO_KEY, admin);
			session.saveOrUpdate(admin);
			tx.commit();
			pageforward="success";
		} catch (Exception e) {
			if(tx!=null) tx.rollback();
			e.printStackTrace();
			ActionErrors actionErrors=new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError("errors.SQLError"));
			return new ActionForward(mapping.getInput());
		} finally {
			session.close();
		}
		return mapping.findForward(pageforward);
	}
}