/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.jwy.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.MisConstants;
import org.chd.struts.jwy.form.JwyQueryForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * MyEclipse Struts Creation date: 03-25-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/jwy/JwyQueryAction" name="JwyQueryForm"
 *                input="/jwy/index.jsp" scope="request" validate="true"
 */
public class JwyQueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		JwyQueryForm JwyQueryForm = (JwyQueryForm) form;
		int nowpage = Integer.parseInt(JwyQueryForm.getNowpage());
		String pageforward = "";
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		try {
			tx = session.beginTransaction();
			Integer rscount = (Integer) session.createQuery(
					"select count(*) from SubjectInfo s").uniqueResult();
			int totalpage = 0;
			if (rscount % MisConstants.PAGESIZE != 0)
				totalpage = rscount.intValue() / (MisConstants.PAGESIZE) + 1;
			else
				totalpage = rscount / MisConstants.PAGESIZE;
			if (nowpage <= 0)
				nowpage = 1;
			if (nowpage >= totalpage)
				nowpage = totalpage;
			int firstResult = (nowpage - 1) * MisConstants.PAGESIZE;
			List subject_list = session.createQuery("from SubjectInfo")
					.setFirstResult(firstResult).setMaxResults(
							MisConstants.PAGESIZE).list();
			// List major_list = session.createQuery("from MajorInfo").list();
			request.setAttribute(MisConstants.SUBJECTLIST_KEY, subject_list);
			request.setAttribute(MisConstants.TOTALPAGE_KEY, totalpage);
			request.setAttribute(MisConstants.NOWPAGE_KEY, nowpage);
			pageforward = "success";
			tx.commit();
		} catch (Exception e) {
			if (tx != null)
				tx.rollback();
			pageforward = "failure";
		} finally {
			session.close();
		}
		ActionForward ActionForward = mapping.findForward(pageforward);
		return ActionForward;

	}
}