package org.chd.entity;
import java.sql.Date;


/**
 * AbstractRequirement generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractRequirement  implements java.io.Serializable {


    // Fields    

     private Integer subjectId;
     private String content;
     private String information;
     private String specification;
     private String charts;
     private String schedule;
     private String reference;
     private Date addDate;


    // Constructors

    /** default constructor */
    public AbstractRequirement() {
    }

	/** minimal constructor */
    public AbstractRequirement(Integer subjectId) {
        this.subjectId = subjectId;
    }
    
    /** full constructor */
    public AbstractRequirement(Integer subjectId, String content, String information, String specification, String charts, String schedule, String reference, Date addDate) {
        this.subjectId = subjectId;
        this.content = content;
        this.information = information;
        this.specification = specification;
        this.charts = charts;
        this.schedule = schedule;
        this.reference = reference;
        this.addDate = addDate;
    }

   
    // Property accessors

    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getInformation() {
        return this.information;
    }
    
    public void setInformation(String information) {
        this.information = information;
    }

    public String getSpecification() {
        return this.specification;
    }
    
    public void setSpecification(String specification) {
        this.specification = specification;
    }

    public String getCharts() {
        return this.charts;
    }
    
    public void setCharts(String charts) {
        this.charts = charts;
    }

    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }

    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
   








}