package org.chd.entity;



/**
 * AbstractLevelA generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractLevelA  implements java.io.Serializable {


    // Fields    

     private LevelAId id;
     private String grade;


    // Constructors

    /** default constructor */
    public AbstractLevelA() {
    }

	/** minimal constructor */
    public AbstractLevelA(LevelAId id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractLevelA(LevelAId id, String grade) {
        this.id = id;
        this.grade = grade;
    }

   
    // Property accessors

    public LevelAId getId() {
        return this.id;
    }
    
    public void setId(LevelAId id) {
        this.id = id;
    }

    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
   








}