package org.chd.entity;
// Generated by MyEclipse - Hibernate Tools



/**
 * LevelA generated by MyEclipse - Hibernate Tools
 */
public class LevelA extends AbstractLevelA implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public LevelA() {
    }

	/** minimal constructor */
    public LevelA(LevelAId id) {
        super(id);        
    }
    
    /** full constructor */
    public LevelA(LevelAId id, String grade) {
        super(id, grade);        
    }
   
}
