package org.chd.entity;



/**
 * LevelAId generated by MyEclipse - Hibernate Tools
 */

public class LevelAId  implements java.io.Serializable {


    // Fields    

     private Integer subjectId;
     private String teacherId;


    // Constructors

    /** default constructor */
    public LevelAId() {
    }

    

   
    // Property accessors

    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
   



   @Override
public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LevelAId) ) return false;
		 LevelAId castOther = ( LevelAId ) other; 
         
		 return ( (this.getSubjectId()==castOther.getSubjectId()) || ( this.getSubjectId()!=null && castOther.getSubjectId()!=null && this.getSubjectId().equals(castOther.getSubjectId()) ) )
 && ( (this.getTeacherId()==castOther.getTeacherId()) || ( this.getTeacherId()!=null && castOther.getTeacherId()!=null && this.getTeacherId().equals(castOther.getTeacherId()) ) );
   }
   
   @Override
public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSubjectId() == null ? 0 : this.getSubjectId().hashCode() );
         result = 37 * result + ( getTeacherId() == null ? 0 : this.getTeacherId().hashCode() );
         return result;
   }   





}