package org.chd.entity;
// Generated by MyEclipse - Hibernate Tools

import java.sql.Date;


/**
 * Requirement generated by MyEclipse - Hibernate Tools
 */
public class Requirement extends AbstractRequirement implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Requirement() {
    }

    
    /** full constructor */
    public Requirement(Integer subjectId,String content, String information, String specification, String charts, String schedule, String reference, Date addDate) {
        super(subjectId, content, information, specification, charts, schedule, reference, addDate);        
    }
   
}
