/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.stu.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.SubjectInfo;
import org.chd.struts.stu.form.OpeningReportForm;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2007
 * 
 * XDoclet definition:
 * @struts.action path="/stu/showOpeningReport" name="OpeningReportForm" input="/stu/index.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/stu/opening_report.jsp" redirect="true"
 * @struts.action-forward name="failure" path="/error.jsp" redirect="true" contextRelative="true"
 */
public class OpengingReportAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		OpeningReportForm OpeningReportForm = (OpeningReportForm) form;
		String studentId=OpeningReportForm.getStudentId();
		String pageforward=null;
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		try {
			tx = session.beginTransaction();
			Query query=session.createQuery("from SubjectInfo where studentId=:studentId");
			query.setString("studentId", studentId);
			SubjectInfo subject=(SubjectInfo)query.uniqueResult();
			if(subject==null)
			{
				ActionErrors actionErrors = new ActionErrors();
				actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError(
						"errors.SQLError"));
				pageforward="wxkt";
			}
			else
			{
			request.setAttribute("OpeningReport",subject);
			if(subject!=null)System.out.println(subject.getSubjectId());
			pageforward = "success";
			}
			tx.commit();
		}catch(Exception e)
		{
			if (tx != null)
				tx.rollback();
			e.printStackTrace();
			pageforward="failure";
		}
		finally{
			session.close();
		}
		return mapping.findForward(pageforward);
	}
}