/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.stu.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.TeacherInfo;
import org.chd.struts.stu.form.ShowTeaInfoForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 10-19-2006
 * 
 * XDoclet definition:
 * @struts.action path="/stu/ShowTeaInfo" name="ShowTeaInfoForm" input="/stu/student_select.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/stu/stu_tea_info.jsp" redirect="true"
 */
public class ShowTeaInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ShowTeaInfoForm ShowTeaInfoForm = (ShowTeaInfoForm) form;
		String teacherId=ShowTeaInfoForm.getTeacherId();
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		String pageforward = "";
		try {
			tx = session.beginTransaction();
			TeacherInfo teacher =(TeacherInfo)session.get(TeacherInfo.class,teacherId);
			request.setAttribute("StuTeaInfo", teacher);
			tx.commit();
			pageforward = "success";
		} catch (Exception e) {
			e.printStackTrace();
			if (tx != null)
				tx.rollback();
			ActionErrors actionErrors = new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError(
					"errors.SQLError"));
			ActionForward returnActionForward = new ActionForward(mapping
					.getInput());
			return returnActionForward;
		} finally {
			session.close();
		}
		ActionForward returnActionForward = mapping.findForward(pageforward);
		return returnActionForward;
	}
}