/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.stu.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.MisConstants;
import org.chd.entity.StudentInfo;
import org.chd.struts.stu.form.StuInfoModForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 10-18-2006
 * 
 * XDoclet definition:
 * @struts.action path="/stu/StuInfoMod" name="StuInfoModForm" input="/stu/stu_info_modify.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/stu/stu_info.jsp" redirect="true"
 */
public class StuInfoModAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StuInfoModForm StuInfoModForm = (StuInfoModForm) form; 
		String studentPhone=StuInfoModForm.getStudentPhone();
		String studentEmail=StuInfoModForm.getStudentEmail();
		String studentId=StuInfoModForm.getStudentId();
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		String pageforward = "";
		try {
			tx = session.beginTransaction();
			StudentInfo student =(StudentInfo)session.get(StudentInfo.class,studentId);
			student.setStudentPhone(studentPhone);
			student.setStudentEmail(studentEmail);
			session.save(student);
			request.getSession().setAttribute(MisConstants.STUDENTINFO_KEY, student);
			tx.commit();
			pageforward = "success";
		} catch (Exception e) {
			e.printStackTrace();
			if (tx != null)
				tx.rollback();
			ActionErrors actionErrors = new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError(
					"errors.SQLError"));
			ActionForward returnActionForward = new ActionForward(mapping
					.getInput());
			return returnActionForward;
		} finally {
			session.close();
		}
		ActionForward returnActionForward = mapping.findForward(pageforward);
		return returnActionForward;
	}
}