/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.stu.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.SubjectInfo;
import org.chd.struts.stu.form.StuMarkShowForm;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 10-18-2006
 * 
 * XDoclet definition:
 * @struts.action path="/stu/StuMarkShow" name="StuMarkShowForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/stu/stu_mark_show.jsp" redirect="true"
 */
public class StuMarkShowAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StuMarkShowForm StuMarkShowForm = (StuMarkShowForm) form;
		String studentId=StuMarkShowForm.getStudentId();
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		String pageforward = "";
		try {
			tx = session.beginTransaction();
			Query query=session.createQuery("from SubjectInfo where studentId=:studentId");
			query.setString("studentId", studentId);
			SubjectInfo subject=(SubjectInfo)query.uniqueResult();
			if(subject==null)
			{
				ActionErrors actionErrors = new ActionErrors();
				actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError(
						"errors.SQLError"));
				pageforward="wxkt";
			}
			else
			{
			session.save(subject);		
			request.setAttribute("StudentSubject",subject);
			pageforward = "success";
			}
			tx.commit();
		} catch (Exception e) {
			
			if (tx != null)
				tx.rollback();
			    pageforward="failure";
			
		} finally {
			session.close();
		}
		ActionForward returnActionForward = mapping.findForward(pageforward);
		return returnActionForward;
	}
}