/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.stu.action;

import java.io.FileNotFoundException;
import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;
import org.chd.UploadUtil;
import org.chd.struts.stu.form.StuPaperUploadForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-20-2006
 * 
 * XDoclet definition:
 * @struts.action path="/stu/StuPaperUpload" name="StuPaperUploadForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="upload_success.jsp" redirect="true"
 */
public class StuPaperUploadAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 * @throws FileNotFoundException 
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws FileNotFoundException, IOException {
		StuPaperUploadForm StuPaperUploadForm = (StuPaperUploadForm) form;		
		FormFile file = StuPaperUploadForm.getStuPaper();
		String pageforward="failure";
//		String contentType = file.getContentType();
		String fileName = file.getFileName();
		int fileSize = file.getFileSize();
		byte[] fileData = file.getFileData();
		try
		{
		UploadUtil.saveFile(getPath("fileUpload") + fileName, fileData, fileSize, FILE_DEST);
		pageforward="success";
		}catch(Exception e)
		{
			pageforward="failure";
		}
		
		return mapping.findForward(pageforward);
	}
}