/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.stu.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.MisConstants;
import org.chd.entity.SubjectInfo;
import org.chd.struts.stu.form.StuSubjectShowForm;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/** 
 * MyEclipse Struts
 * Creation date: 04-24-2007
 * 
 * XDoclet definition:
 * @struts.action path="/stu/subjectShow" name="StuSubjectShowForm" input="/stu/index.jsp" scope="request" validate="true"
 * @struts.action-forward name="wxkt" path="/stu/wxkt.html" redirect="true"
 * @struts.action-forward name="success" path="/stu/stu_subject_show.jsp"
 * @struts.action-forward name="failure" path="/error.jsp" redirect="true"
 */
public class StuSubjectShowAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StuSubjectShowForm StuSubjectShowForm = (StuSubjectShowForm) form;
		String pageforward="";
		String studentId=StuSubjectShowForm.getStudentId();
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		try {
			tx = session.beginTransaction();
			Criteria criteria2 = session.createCriteria(SubjectInfo.class);
			criteria2.add(Restrictions.eq("studentId", studentId));
			SubjectInfo subject=(SubjectInfo)criteria2.uniqueResult();
			if(subject!=null)
			{
			request.setAttribute(MisConstants.SUBJETINFO_KEY,subject);
			pageforward = "success";
			}
			else
			{
				pageforward="wxkt";
			}
		} catch (Exception e) {
			if (tx != null)
				e.printStackTrace();
				tx.rollback();
			ActionErrors actionErrors = new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError(
					"errors.SQLError"));
			ActionForward returnActionForward = new ActionForward(mapping
					.getInput());
			return returnActionForward;
		} finally {
			session.close();
		}
		ActionForward returnActionForward = mapping.findForward(pageforward);
		return returnActionForward;
	}
}