/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.stu.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.chd.HibernateSessionFactory;
import org.chd.entity.SubjectInfo;
import org.chd.struts.stu.form.StuSubjectCancelForm;
import org.hibernate.Session;
import org.hibernate.Transaction;

/** 
 * MyEclipse Struts
 * Creation date: 10-19-2006
 * 
 * XDoclet definition:
 * @struts.action path="/stu/StuSubjectCancel" name="StuSubjectCancelForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/stu/student_select.jsp" redirect="true"
 */
public class StuSubjectCancelAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StuSubjectCancelForm StuSubjectCancelForm = (StuSubjectCancelForm) form;
		
		String temp=StuSubjectCancelForm.getSubjectId();
		Integer subjectId=Integer.parseInt(temp);
		String pageforward =null;
		Session session = HibernateSessionFactory.getSession();
		Transaction tx = null;
		try {
			 tx = session.beginTransaction();
			 SubjectInfo subject=(SubjectInfo)session.get(SubjectInfo.class, subjectId);
			 subject.setStudentId(null);
			 session.saveOrUpdate(subject);
			 tx.commit();
			 pageforward = "success";
		} catch (Exception e) {
			if (tx != null)
				e.printStackTrace();
				tx.rollback();
			ActionErrors actionErrors = new ActionErrors();
			actionErrors.add(ActionErrors.GLOBAL_ERROR, new ActionError(
					"errors.SQLError"));
			ActionForward returnActionForward = new ActionForward(mapping
					.getInput());
			return returnActionForward;
		} finally {
			session.close();
		}
		ActionForward returnActionForward = mapping.findForward(pageforward);
		return returnActionForward;
	}
}