/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-03-2006
 * 
 * XDoclet definition:
 * @struts.form name="AddNotesForm"
 */
public class AddNotesForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** notes property */
	
	private String news;
     
	private String newsName;
	
	private String majorName;
	/*
	 * Generated Methods
	 */

	public String getMajorName() {
		return majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	public String getNewsName() {
		return newsName;
	}

	public void setNewsName(String newsName) {
		this.newsName = newsName;
	}


	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors=super.validate(mapping, request);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.majorName=null;
		this.newsName=null;
		this.news=null;
	}

	/** 
	 * Returns the notes.
	 * @return String
	 */
	public String getNews() {
		return news;
	}

	/** 
	 * Set the notes.
	 * @param notes The notes to set
	 */
	public void setNews(String news) {
		this.news = news;
	}
}