/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-02-2006
 * 
 * XDoclet definition:
 * @struts.form name="JwyRegistrationAction"
 */
public class JwyRegistrationForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** jwy_id property */
	private String jwy_id;

	/** jwy_password property */
	private String jwy_password;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors=super.validate(mapping, request);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.jwy_id=null;
		this.jwy_password=null;
	}

	/** 
	 * Returns the jwy_id.
	 * @return String
	 */
	public String getJwy_id() {
		return jwy_id;
	}

	/** 
	 * Set the jwy_id.
	 * @param jwy_id The jwy_id to set
	 */
	public void setJwy_id(String jwy_id) {
		this.jwy_id = jwy_id;
	}

	/** 
	 * Returns the jwy_password.
	 * @return String
	 */
	public String getJwy_password() {
		return jwy_password;
	}

	/** 
	 * Set the jwy_password.
	 * @param jwy_password The jwy_password to set
	 */
	public void setJwy_password(String jwy_password) {
		this.jwy_password = jwy_password;
	}
}