/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2006
 * 
 * XDoclet definition:
 * @struts.form name="ShowMarkForm"
 */
public class ShowMarkForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** studentId property */
	private String id;

	private String queryway;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the studentId.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the studentId.
	 * @param studentId The studentId to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	public String getQueryway() {
		return queryway;
	}

	public void setQueryway(String queryway) {
		this.queryway = queryway;
	}
}