/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2006
 * 
 * XDoclet definition:
 * @struts.form name="ShowSubjectForm"
 */
public class ShowSubjectForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** nowPage property */
	private String nowPage;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the nowPage.
	 * @return String
	 */
	public String getNowPage() {
		return nowPage;
	}

	/** 
	 * Set the nowPage.
	 * @param nowPage The nowPage to set
	 */
	public void setNowPage(String nowPage) {
		this.nowPage = nowPage;
	}
}