/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-16-2006
 * 
 * XDoclet definition:
 * @struts.form name="ShowSubjectBySortForm"
 */
public class ShowSubjectBySortForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** sortname property */
	private String sortname;
	
	private String teacherId;
	
	private String fieldName;
	
	private String difficulty;

	/*
	 * Generated Methods
	 */

	public String getDifficulty() {
		return difficulty;
	}

	public void setDifficulty(String difficulty) {
		this.difficulty = difficulty;
	}

	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sortname.
	 * @return String
	 */
	public String getSortname() {
		return sortname;
	}

	/** 
	 * Set the sortname.
	 * @param sortname The sortname to set
	 */
	public void setSortname(String sortname) {
		this.sortname = sortname;
	}
}