/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-25-2006
 * 
 * XDoclet definition:
 * @struts.form name="StudentRegistrationForm"
 */
public class StudentRegistrationForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** studentId property */
	private String studentId;

	/** studentPassword property */
	private String studentPassword;

	/** studentName property */
	private String studentName;

	/** majorId property */
	private String majorName;

	/** studentSex property */
	private String studentSex;
	
	private String studentClass;
	
	private String studentPhone;
	
	private String studentEmail;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors=super.validate(mapping, request);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.majorName=null;
		this.studentClass=null;
		this.studentEmail=null;
		this.studentId=null;
		this.studentName=null;
		this.studentPassword=null;
		this.studentPhone=null;
		this.studentSex=null;
	}

	/** 
	 * Returns the studentId.
	 * @return String
	 */
	public String getStudentId() {
		return studentId;
	}

	/** 
	 * Set the studentId.
	 * @param studentId The studentId to set
	 */
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	/** 
	 * Returns the studentPassword.
	 * @return String
	 */
	public String getStudentPassword() {
		return studentPassword;
	}

	/** 
	 * Set the studentPassword.
	 * @param studentPassword The studentPassword to set
	 */
	public void setStudentPassword(String studentPassword) {
		this.studentPassword = studentPassword;
	}

	/** 
	 * Returns the studentName.
	 * @return String
	 */
	public String getStudentName() {
		return studentName;
	}

	/** 
	 * Set the studentName.
	 * @param studentName The studentName to set
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	/** 
	 * Returns the majorId.
	 * @return String
	 */
	public String getMajorName() {
		return majorName;
	}

	/** 
	 * Set the majorId.
	 * @param majorId The majorId to set
	 */
	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	/** 
	 * Returns the studentSex.
	 * @return String
	 */
	public String getStudentSex() {
		return studentSex;
	}

	/** 
	 * Set the studentSex.
	 * @param studentSex The studentSex to set
	 */
	public void setStudentSex(String studentSex) {
		this.studentSex = studentSex;
	}

	public String getStudentClass() {
		return studentClass;
	}

	public void setStudentClass(String studentClass) {
		this.studentClass = studentClass;
	}

	public String getStudentEmail() {
		return studentEmail;
	}

	public void setStudentEmail(String studentEmail) {
		this.studentEmail = studentEmail;
	}

	public String getStudentPhone() {
		return studentPhone;
	}

	public void setStudentPhone(String studentPhone) {
		this.studentPhone = studentPhone;
	}
}