/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-02-2006
 * 
 * XDoclet definition:
 * @struts.form name="TeacherInfoModifyForm"
 */
public class TeacherInfoModifyForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** teacherName property */
	private String teacherName;

	/** teacherPhone property */
	private String teacherPhone;

	/** teacherPassword property */
	private String teacherPassword;

	/** teacherEmail property */
	private String teacherEmail;

	/** fieldName property */
	private String fieldName;

	/** teacherSex property */
	private String teacherSex;

	/** teacherId property */
	private String teacherId;

	/** post property */
	private String post;

	private String majorName;
	/*
	 * Generated Methods
	 */

	public String getMajorName() {
		return majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors=super.validate(mapping, request);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.fieldName=null;
		this.majorName=null;
		this.post=null;
		this.teacherEmail=null;
		this.teacherId=null;
		this.teacherName=null;
		this.teacherPassword=null;
		this.teacherPhone=null;
		this.teacherSex=null;
	}

	/** 
	 * Returns the teacherName.
	 * @return String
	 */
	public String getTeacherName() {
		return teacherName;
	}

	/** 
	 * Set the teacherName.
	 * @param teacherName The teacherName to set
	 */
	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	/** 
	 * Returns the teacherPhone.
	 * @return String
	 */
	public String getTeacherPhone() {
		return teacherPhone;
	}

	/** 
	 * Set the teacherPhone.
	 * @param teacherPhone The teacherPhone to set
	 */
	public void setTeacherPhone(String teacherPhone) {
		this.teacherPhone = teacherPhone;
	}

	/** 
	 * Returns the teacherPassword.
	 * @return String
	 */
	public String getTeacherPassword() {
		return teacherPassword;
	}

	/** 
	 * Set the teacherPassword.
	 * @param teacherPassword The teacherPassword to set
	 */
	public void setTeacherPassword(String teacherPassword) {
		this.teacherPassword = teacherPassword;
	}

	/** 
	 * Returns the teacherEmail.
	 * @return String
	 */
	public String getTeacherEmail() {
		return teacherEmail;
	}

	/** 
	 * Set the teacherEmail.
	 * @param teacherEmail The teacherEmail to set
	 */
	public void setTeacherEmail(String teacherEmail) {
		this.teacherEmail = teacherEmail;
	}

	/** 
	 * Returns the fieldName.
	 * @return String
	 */
	public String getFieldName() {
		return fieldName;
	}

	/** 
	 * Set the fieldName.
	 * @param fieldName The fieldName to set
	 */
	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	/** 
	 * Returns the teacherSex.
	 * @return String
	 */
	public String getTeacherSex() {
		return teacherSex;
	}

	/** 
	 * Set the teacherSex.
	 * @param teacherSex The teacherSex to set
	 */
	public void setTeacherSex(String teacherSex) {
		this.teacherSex = teacherSex;
	}

	/** 
	 * Returns the teacherId.
	 * @return String
	 */
	public String getTeacherId() {
		return teacherId;
	}

	/** 
	 * Set the teacherId.
	 * @param teacherId The teacherId to set
	 */
	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	/** 
	 * Returns the post.
	 * @return String
	 */
	public String getPost() {
		return post;
	}

	/** 
	 * Set the post.
	 * @param post The post to set
	 */
	public void setPost(String post) {
		this.post = post;
	}
}