/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.chd.struts.adm.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-02-2006
 * 
 * XDoclet definition:
 * @struts.form name="UserInfoModify"
 */
public class UserInfoModifyForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** studentId property */
	private String studentId;

	/** adminId property */
	private String adminId;

	/** teacherId property */
	private String teacherId;

	
	private String identity;
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the studentId.
	 * @return String
	 */
	public String getStudentId() {
		return studentId;
	}

	/** 
	 * Set the studentId.
	 * @param studentId The studentId to set
	 */
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	/** 
	 * Returns the adminId.
	 * @return String
	 */
	public String getAdminId() {
		return adminId;
	}

	/** 
	 * Set the adminId.
	 * @param adminId The adminId to set
	 */
	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	/** 
	 * Returns the teacherId.
	 * @return String
	 */
	public String getTeacherId() {
		return teacherId;
	}

	/** 
	 * Set the teacherId.
	 * @param teacherId The teacherId to set
	 */
	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	/**
	 * @return the identity
	 */
	public String getIdentity() {
		return identity;
	}

	/**
	 * @param identity the identity to set
	 */
	public void setIdentity(String identity) {
		this.identity = identity;
	}
}